os: osx
addons:
  homebrew:
    packages:
      - qt
      - zip
script:
  - mkdir cbuild
  - cd cbuild
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
after_success:
  - zip output/MyQtAoo.app
before_deploy:
- git config --local user.name "Rayxuln"
- git config --local user.email "imbosslx@sina.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: bEJOLfZcYXUqje3BgEVE+wRtakS1/kx8/ZOcrIOEe9vfuw+LLFYmENDvcDMHe/t4z4S4S/nr/A5O7rYrmSH8TpdqU036vYJkbDhi1aNh5ye3X08AZbHA6LosNfV5SmECZHkTgqCzqL9mZ97FW0cizuTP3/lXePovsh4aHnbvODsco6Q8MuCP0pDxhu4PiOCJmR/slO11d9Wzg9ZHLFhYerg9Q5EEz+wG3ijKj4FVunZi6UarJHH89geIBSwVWKB3X3nQ439rWFJ+MR+n0/FdvLKsOIkUd8364HS7Kf4eNM5Ydrg+MZbrCtEP1tBxE4ODj96QoJLfsvVsJfLhSoldqPyWWjvrPuhtimuwlkj5xhrLSp5Ta1Iwp4uZDQNWBF4Ut20BI3krW8m8ZmKAESafsRORqPLMiEpd6rxYfUgpF7lfiVY0d9r6j9V83A3bJoAyyuSSM66G7YaWZnw34fyC6Y72Nk2G7UG4p+syKvtyLfxT2ZSIWeanaCpZ1cIV4G0JYUoCXj9QEpEIjsaUZNiWOAdYVmbOw/5GUPWHh2zPPsUI2eKJ/5gq3w2pjSvxiK03H39wj/0dH/pc8VE8GaPpEZohujDonvJScnXe4vSXTUWxZ3RT5nYC8iwFOoM+owlo42G4v63exIJ/0s6Lm/vL9PcCB6JANQCAWIAaNB+n+wE=
  file: output/MyQtAoo.zip
  skip_cleanup: true
  on:
    tags: on
    repo: rayxuln/MyQtMultiPlatform0